server:
  port: ${PORT:8090}
spring:
  application:
    name: spring-boot-coding-assignment
  devtools:
    restart:
      enabled: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

exchange:
  rates:
    url: https://api.apilayer.com/exchangerates_data/latest?symbols=EUR,USD,SEK&base=EUR
    apiKey: <REPLACE_ME>

